name: Windows Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-on-windows:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run tests and generate HTML report
        run: |
          mkdir test-reports
          pytest --html=test-reports/report.html --self-contained-html

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-reports/report.html
