name: Windows Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-on-windows:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you are using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure you have a requirements.txt

      # Step 4: Run tests with pytest and generate HTML report
      - name: Run tests and generate HTML report
        run: |
          mkdir test-reports
          pytest --html=test-reports/report.html --self-contained-html

      # Step 5: Upload the HTML report as an artifact
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-reports/report.html
