name: Windows Tests with Prioritized Failed Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-on-windows:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html

      # Restore the cache of previously failed tests
      - name: Restore failed test cache
        id: cache-failed-tests
        uses: actions/cache@v3
        with:
          path: ./.pytest_cache
          key: failed-tests-${{ github.ref }}  # Cache by branch to restore across runs on the same branch

      # Run only previously failed tests if cache exists
      - name: Run prioritized failed tests (if any)
        if: steps.cache-failed-tests.outputs.cache-hit == 'true'
        run: |
          mkdir -p test-reports
          pytest --last-failed --html=test-reports/failed-tests-report.html --self-contained-html || exit 1

      # Run all tests if no failed tests were found in the cache or if prioritized tests pass
      - name: Run all tests and generate full HTML report
        if: steps.cache-failed-tests.outputs.cache-hit != 'true' || success()
        run: |
          mkdir -p test-reports
          pytest --html=test-reports/full-report.html --self-contained-html

      # Save failed test cases for the next run
      - name: Save failed test cache
        if: failure()
        run: echo "Caching failed tests for future runs..."

      # Upload the HTML reports as artifacts
      - name: Upload test report artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-reports/

      # Upload the .pytest_cache as an artifact for inspection
      - name: Upload failed test cache as artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-cache
          path: ./.pytest_cache
