name: Test with Prioritized Failed Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-on-windows:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html

      # Download the HTML report from the previous run
      - name: Download previous test report artifact
        uses: actions/download-artifact@v3
        with:
          name: test-report
          path: previous-test-report
        continue-on-error: true  # If there's no previous artifact, don't fail

      # Parse the previous HTML report for failed tests and store them in a file
      - name: Extract failed tests from previous run
        run: |
          python parse_html_report.py previous-test-report/report.html failed_tests.txt
        continue-on-error: true

      # Conditionally run only the previously failed tests if they exist
      - name: Run prioritized failed tests (if any)
        if: ${{ success() && steps.extract-failed-tests.outputs.file-exists == 'true' }}
        run: |
          pytest --html=test-reports/priority-report.html --self-contained-html --maxfail=1 $(< failed_tests.txt)

      # Run all tests and generate a full HTML report
      - name: Run all tests and generate full HTML report
        run: |
          pytest --html=test-reports/report.html --self-contained-html

      # Upload HTML report as artifact
      - name: Upload test report artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-reports/*.html
